[package]
name = "hsh"
version = "0.0.1"
edition = "2021"

[dependencies]
rustyline = "14.0.0"
rustyline-derive = "0.10.0"
chrono = "0.4.38"
brush-shell = "0.3.0"
hk-parser = "0.2.1"
libc = "0.2.155"
shlex = "1.3.0"
